Remove ct-dirtycontainers-values.yaml
Because it fails like this:

```
Installing chart with values file "charts/surrealdb/ci/ct-dirtycontainers-values.yaml"...

Creating namespace "surrealdb-gg9zyrifhw"...
namespace/surrealdb-gg9zyrifhw created
Error: INSTALLATION FAILED: 1 error occurred:
	* Deployment.apps "surrealdb-gg9zyrifhw" is invalid: [spec.template.spec.containers[1].image: Required value, spec.template.spec.initContainers[0].image: Required value]

```